extends:
  - next/core-web-vitals
  - eslint:recommended
  - plugin:react/recommended
plugins:
  - react
rules:
  linebreak-style:
    - error
    - unix
overrides:
  - files:
      - "*.tsx"
    rules:
      "react/react-in-jsx-scope": "off"
      "react/prop-types": "off"