extends:
  - next/core-web-vitals
  - eslint:recommended
  - plugin:react/recommended
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
plugins:
  - react
  - "@typescript-eslint"
ignorePatterns: 
  - "**/__generated__/**"
  - "**/___generated__/**"
rules:
  linebreak-style:
    - error
    - unix
overrides:
  - files:
      - "*.tsx"
    rules:
      "react/react-in-jsx-scope": "off"
      "react/prop-types": "off"