tasks:
  - name: "Dev"
    init: yarn && gp sync-done install
    command: yarn dev
  - name: Watch graphql
    command: gp sync-await install && yarn graphql-watch
ports:
  - port: 3000
    visibility: private
    onOpen: open-browser
    name: Next app
    description: OCTAV3 Next App

