tasks:
  - name: "Dev"
    init: yarn
    command: yarn dev
  - name: Watch graphql
    command: yarn graphql-watch
ports:
  - port: 3000
    visibility: private
    onOpen: open-browser
    name: Next app
    description: OCTAV3 Next App

