import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const client = new ApolloClient({
    uri: GraphQLEndpoint,
    cache: new InMemoryCache(),
  });
  const getLayout = Component.getLayout ?? ((page) => page);
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )


  return (
    <>
      <Script src="https://code.iconify.design/3/3.0.0/iconify.min.js" />
      <WagmiConfig config={wagmiClient}>
        <RainbowKitProvider
          chains={chains}
          theme={lightTheme({
            accentColor: "#F3EA01",
            accentColorForeground: "#313131",
          })}
        >
          <ApolloProvider client={client}>
            <ThemeProvider attribute="class">
              <MusicPlayer />
              <Header />
              {getLayout(<Component {...pageProps} />)}
            </ThemeProvider>
          </ApolloProvider>
        </RainbowKitProvider>
      </WagmiConfig>
    </>
  );
}
