name: "Lint and build"
on: push

jobs:
  build:
    name: Build next app
    runs-on: ubuntu-latest
    env:
     NEXT_PUBLIC_NFT_STORAGE_TOKEN: ${{ secrets.NEXT_PUBLIC_NFT_STORAGE_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: |
          yarn
          rm -rf __generated__
          yarn build
  lint:
    name: Lint next app
    runs-on: ubuntu-latest
    env:
     NEXT_PUBLIC_NFT_STORAGE_TOKEN: ${{ secrets.NEXT_PUBLIC_NFT_STORAGE_TOKEN }}

    steps:
      - name: Check out code and lint
        uses: actions/checkout@v2
      - name: Install package
        run: |
          yarn install --frozen-lockfile
          rm -rf __generated__
          yarn lint --max-warnings=0
